# Generated by Django 4.1.7 on 2023-04-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='myportfolio/files/covers')),
                ('sourcelink', models.CharField(blank=True, max_length=200, null=True)),
                ('livelink', models.CharField(blank=True, max_length=200, null=True)),
                ('rank', models.IntegerField()),
                ('category', models.CharField(choices=[('none', 'None'), ('mobile', 'Mobile'), ('web', 'WEB')], default='None', max_length=10)),
                ('tags', models.ManyToManyField(to='myportfolio.tag')),
                ('tools', models.ManyToManyField(to='myportfolio.tool')),
            ],
        ),
    ]
